"use client";

import { WorkspaceLink as Link } from "@/components/app/workspace-link";
import { ArrowRight, CheckCircle2, Clock3, LockKeyhole, Workflow } from "lucide-react";
import { PageHeader } from "@/components/app/page-header";
import { NewWorkflowButton } from "@/components/app/new-workflow-button";
import { useDemoStore } from "@/components/app/demo-store";
import { demoWorkflowId } from "@/lib/demo-fixture";

export function DemoIntro() {
  return <section className="mb-7 flex flex-wrap items-center justify-between gap-4 border-b border-border pb-6" aria-label="Product introduction"><div className="max-w-2xl"><p className="section-label">An auditable sales operations workflow</p><h2 className="mt-2 text-lg font-semibold tracking-tight">From a business goal to research, review and action.</h2><p className="mt-2 text-xs leading-6 text-muted-foreground">Explore one historical sample in three minutes. Agents prepare evidence and proposals; people authorize external actions. Every result has an execution record.</p></div><Link href={`/demo/workflows/${demoWorkflowId}`} className="inline-flex items-center gap-2 rounded-md border border-border bg-card px-3 py-2 text-xs font-medium hover:bg-muted">Inspect the showcase<ArrowRight className="size-3.5" /></Link></section>;
}

export function DemoIntelligence() {
  const { companies, leads, approvals } = useDemoStore();
  const actions = approvals.flatMap((approval) => approval.proposedActions);
  const metrics = [["Researched", companies.filter((company) => company.researchStatus === "researched").length], ["Qualified", leads.filter((lead) => (lead.score ?? 0) >= 60).length], ["Drafts", actions.length], ["Simulated executions", actions.filter((action) => action.status === "executed").length]] as const;
  return <div className="flex flex-col gap-6"><PageHeader eyebrow="Sample outcomes" title="Intelligence" description="A funnel calculated from the fictional records in this demo. Real workspace analytics use persisted database records." />
    <section className="panel p-5" aria-labelledby="sample-funnel-title"><h2 id="sample-funnel-title" className="text-sm font-semibold">Research to approved action</h2><dl className="mt-5 grid grid-cols-2 gap-5 md:grid-cols-4">{metrics.map(([label, value]) => <div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-2 font-mono text-3xl tabular-nums">{value}</dd><div aria-hidden className="mt-3 h-1.5 bg-muted"><div className="h-full bg-[var(--brand-accent)]" style={{ width: `${value / Math.max(companies.length, 1) * 100}%` }} /></div></div>)}</dl><p className="mt-5 text-xs leading-6 text-muted-foreground">Execution is historical simulation only. No email was delivered. Local approval decisions update the review queue; they do not add executions.</p></section>
    <div className="table-shell" tabIndex={0} aria-label="Sample opportunity scores, horizontally scrollable"><table className="w-full min-w-[550px] text-left text-xs"><caption className="sr-only">Sample company scores and qualification uncertainty</caption><thead className="border-b border-border bg-muted/40"><tr>{["Company", "Industry", "Score", "Confidence"].map((heading) => <th key={heading} scope="col" className="px-5 py-3 font-medium text-muted-foreground">{heading}</th>)}</tr></thead><tbody>{companies.map((company) => <tr key={company.id} className="interactive-row border-b border-border last:border-0"><th scope="row" className="px-5 py-4 font-medium"><Link href={`/companies?company=${company.id}`} className="hover:underline">{company.name}</Link></th><td className="px-5">{company.industry}</td><td className="px-5 font-mono">{company.score}/100</td><td className="px-5">Medium · sample</td></tr>)}</tbody></table></div>
    <section className="grid gap-5 border-y border-border py-5 sm:grid-cols-3"><div><h2 className="text-xs font-semibold">Evidence before claims</h2><p className="mt-2 text-xs leading-6 text-muted-foreground">Scores illustrate fit and a specific operational need. Purchasing intent and support volume remain unverified.</p></div><div><h2 className="text-xs font-semibold">Usage and cost</h2><p className="mt-2 text-xs leading-6 text-muted-foreground">Not recorded for samples. No AI requests were made. Real cost stays unknown until usage and exact versioned pricing exist.</p></div><div><h2 className="text-xs font-semibold">Reply monitoring</h2><p className="mt-2 text-xs leading-6 text-muted-foreground">Unavailable. A sent or contacted status is not evidence that someone replied.</p></div></section>
    <Link href={`/workflows/${demoWorkflowId}`} className="text-xs font-medium text-[var(--brand-accent)] hover:underline">Inspect the workflow behind these sample outcomes →</Link>
  </div>;
}

export function DemoAutomation() {
  return <div className="flex flex-col gap-6"><PageHeader eyebrow="Historical simulation" title="Automation" description="How a completed action can lead to a new proposal, with bounded retries and a fresh approval gate." />
    <div className="flex items-start gap-3 rounded-md border border-[var(--warning-border)] bg-[var(--warning-bg)] p-4 text-xs leading-6 text-[var(--warning-fg)]"><LockKeyhole className="mt-1 size-4 shrink-0" /><p>Sample history only. No worker, timer, mailbox or provider runs in this demo. A real follow-up requires its own review and explicit Execute.</p></div>
    <section className="panel p-5"><h2 className="text-sm font-semibold">Orda Finance · follow-up story</h2><ol className="mt-5 flex flex-col gap-0">{[
      ["Human reviewed the original revision", "The recipient, account, evidence and message were checked before the sample approval."],
      ["Executor recorded a simulated result", "A separate execution record illustrates the approved action. No message was delivered."],
      ["An independently approved plan scheduled preparation", "The plan points to the original successful action; it does not authorize another email."],
      ["A new draft awaits human review", "The follow-up gets a fresh proposal. Monitoring stays unavailable without a permitted read grant."],
    ].map(([title, description], index) => <li key={title} className="flex gap-4 border-b border-border py-4 last:border-0"><span className="flex size-7 shrink-0 items-center justify-center rounded-full border border-border bg-muted text-[var(--brand-accent)]">{index < 3 ? <CheckCircle2 className="size-3.5" /> : <Clock3 className="size-3.5" />}</span><div><h3 className="text-xs font-medium">{title}</h3><p className="mt-1 text-xs leading-6 text-muted-foreground">{description}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">SIMULATED / RECORDED EXAMPLE</p></div></li>)}</ol></section>
    <div className="grid gap-5 sm:grid-cols-3">{[["Retries", "Temporary failures may retry within a fixed budget; permanent failures need attention."], ["Unknown outcomes", "An uncertain provider result blocks resend until reconciliation. A timeout is not proof of failure."], ["Cancellation", "Future work can be cancelled while confirmed results and audit history remain intact."]].map(([title, copy]) => <section key={title} className="border-t border-border pt-4"><h2 className="text-xs font-semibold">{title}</h2><p className="mt-2 text-xs leading-6 text-muted-foreground">{copy}</p></section>)}</div>
    <Link href="/activity" className="text-xs font-medium text-[var(--brand-accent)] hover:underline">Read the sample activity history →</Link>
  </div>;
}

export const sampleGoal = "Find 3 B2B SaaS and fintech companies in Kazakhstan with a specific customer support automation opportunity. Research and qualify them; prepare outreach for human review. Do not send without approval.";
export function DemoStrategy({ kind }: { kind: "icps" | "templates" }) {
  return <div className="flex flex-col gap-6"><PageHeader eyebrow="Sample strategy" title={kind === "icps" ? "Customer profiles" : "Workflow templates"} description="Read-only example. Saved strategy in real workspaces becomes an immutable snapshot on each new workflow." />
    <article className="panel max-w-3xl p-5 sm:p-6"><span className="section-label">DEMO / SAMPLE · read only</span><h2 className="mt-3 text-base font-semibold">{kind === "icps" ? "Kazakhstan software & fintech teams" : "Research → qualify → prepare outreach"}</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2">{[["Market", "Kazakhstan · B2B SaaS and fintech"], ["Target size", "11–200 employees · confirm with evidence"], ["Opportunity", "Customer support and internal operations"], ["Guardrails", "Retain sources, label uncertainty, require human approval"]].map(([label, value]) => <div key={label}><dt className="section-label">{label}</dt><dd className="mt-2 text-xs leading-6">{value}</dd></div>)}</dl><p className="my-5 border-t border-border pt-4 text-xs leading-6 text-muted-foreground">Explicit goals take priority over template guidance. Changing a saved profile later cannot alter historical research, scores or approvals.</p><NewWorkflowButton initialGoal={sampleGoal} initialTarget={3} label="Try a local workflow draft" /><Link href={`/workflows/${demoWorkflowId}`} className="ml-4 inline-flex items-center gap-1 text-xs text-muted-foreground hover:underline"><Workflow className="size-3" />Inspect showcase</Link></article>
  </div>;
}
