"use client";

import { useMemo, useState } from "react";
import { WorkspaceLink as Link } from "@/components/app/workspace-link";
import { ArrowDownWideNarrow } from "lucide-react";
import type { IntelligenceSegment, UsageIntelligence, WorkflowIntelligence } from "@/types/intelligence";
import { number, money, percent, duration } from "./format";

const th = "whitespace-nowrap px-3 py-3 text-[10px] font-medium text-muted-foreground";
const td = "whitespace-nowrap px-3 py-3 font-mono text-[11px] tabular-nums";
export function WorkflowComparison({ workflows, truncated }: { workflows: WorkflowIntelligence[]; truncated: boolean }) {
  const [sort, setSort] = useState<"qualified" | "averageScore" | "replies" | "estimatedCostUsd" | "createdAt">("createdAt");
  const sorted = useMemo(() => [...workflows].sort((a, b) => sort === "createdAt" ? b.createdAt.localeCompare(a.createdAt) : (b[sort] ?? -1) - (a[sort] ?? -1)), [workflows, sort]);
  return <section className="min-w-0" aria-labelledby="workflow-performance"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h2 id="workflow-performance" className="text-sm font-semibold">Workflow performance</h2><p className="mt-1 text-[11px] text-muted-foreground">Saved outcomes and lifetime estimated cost of the selected cohort.</p></div><label className="flex items-center gap-2 text-xs text-muted-foreground"><ArrowDownWideNarrow className="size-3.5" /><span className="sr-only">Sort workflow comparison</span><select aria-label="Sort workflow comparison" value={sort} onChange={(event) => setSort(event.target.value as typeof sort)} className="h-8 rounded-md border border-input bg-card px-2 text-xs focus-visible:outline-2 focus-visible:outline-ring"><option value="createdAt">Newest workflow</option><option value="qualified">Qualified leads</option><option value="averageScore">Average score</option><option value="replies">Detected replies</option><option value="estimatedCostUsd">Estimated cost</option></select></label></div><div tabIndex={0} role="region" aria-label="Workflow comparison table, scroll horizontally" className="focus-visible:outline-2 focus-visible:outline-ring overflow-x-auto rounded-lg border border-border bg-card"><table className="w-full min-w-[850px] text-left"><thead className="border-b border-border bg-muted/30"><tr>{["Workflow", "Researched", "Qualified", "Avg. score", "Sent", "Replies", "Estimated AI cost", "Cost / lead", "Duration"].map((label) => <th key={label} scope="col" className={th}>{label}</th>)}</tr></thead><tbody className="divide-y divide-border">{sorted.map((workflow) => <tr key={workflow.id} className="hover:bg-muted/25"><td className="max-w-[240px] px-3 py-3"><Link href={`/workflows/${workflow.id}`} className="block truncate text-xs font-medium hover:underline" title={workflow.title}>{workflow.title}</Link><span className="mt-1 block truncate text-[10px] text-muted-foreground">{workflow.icpName ?? "No ICP"} · {workflow.templateName ?? "From goal"}</span></td>{[workflow.researched, workflow.qualified, workflow.averageScore, workflow.sent, workflow.replies].map((value, index) => <td key={index} className={td}>{number(value, index === 2 ? 1 : 0)}</td>)}<td className={td}>{money(workflow.estimatedCostUsd)}{workflow.unknownCostRuns > 0 && <span className="mt-1 block font-sans text-[10px] text-muted-foreground">{workflow.unknownCostRuns} unpriced runs</span>}</td><td className={td}>{money(workflow.costPerQualifiedLead)}</td><td className={td}>{duration(workflow.durationMs)}</td></tr>)}</tbody></table>{!workflows.length && <p className="p-5 text-xs text-muted-foreground">No workflows match this cohort.</p>}</div>{truncated && <p className="mt-2 text-[11px] text-[var(--warning-fg)]">Comparison shows a bounded subset. Narrow the period or select a workflow; summary totals include the full cohort.</p>}</section>;
}

export function SegmentTable({ title, segments }: { title: string; segments: IntelligenceSegment[] }) {
  return <section className="min-w-0"><h3 className="mb-3 text-xs font-semibold">{title}</h3><div tabIndex={0} role="region" aria-label={`${title}, scroll horizontally`} className="focus-visible:outline-2 focus-visible:outline-ring overflow-x-auto rounded-md border border-border bg-card"><table className="w-full min-w-[550px] text-left"><thead className="border-b border-border bg-muted/30"><tr>{["Segment", "Companies", "Qualified", "Avg. score", "High confidence", "Sent", "Replies"].map((label) => <th key={label} scope="col" className={th}>{label}</th>)}</tr></thead><tbody className="divide-y divide-border">{segments.map((segment) => <tr key={segment.key}><th scope="row" className="max-w-[210px] px-3 py-3 text-xs font-normal">{segment.label}</th>{[segment.companies, segment.qualified, segment.averageScore, segment.highConfidence, segment.sent, segment.replies].map((value, index) => <td key={index} className={td}>{number(value, index === 2 ? 1 : 0)}</td>)}</tr>)}</tbody></table>{!segments.length && <p className="p-4 text-xs text-muted-foreground">No recorded outcomes for this segment.</p>}</div></section>;
}

export function UsageTable({ title, rows }: { title: string; rows: UsageIntelligence[] }) {
  return <section className="min-w-0"><h3 className="mb-3 text-xs font-semibold">{title}</h3><div tabIndex={0} role="region" aria-label={`${title}, scroll horizontally`} className="focus-visible:outline-2 focus-visible:outline-ring overflow-x-auto rounded-md border border-border bg-card"><table className="w-full min-w-[750px] text-left"><thead className="border-b border-border bg-muted/30"><tr>{["Name", "Runs", "Completed / terminal", "Failed", "Avg. duration", "Tokens", "Estimated AI cost", "Retries", "Tool calls"].map((label) => <th key={label} scope="col" className={th}>{label}</th>)}</tr></thead><tbody className="divide-y divide-border">{rows.map((row) => <tr key={row.key}><th scope="row" className="max-w-[200px] px-3 py-3 text-xs font-normal">{row.label}</th><td className={td}>{number(row.runs)}</td><td className={td}>{percent(row.successRate)}</td><td className={td}>{number(row.failed)}</td><td className={td}>{duration(row.averageDurationMs)}</td><td className={td}>{number(row.totalTokens)}{row.unknownUsageRuns > 0 && <span className="mt-1 block font-sans text-[10px] text-muted-foreground">{row.unknownUsageRuns} unmeasured</span>}</td><td className={td}>{money(row.estimatedCostUsd)}{row.unknownCostRuns > 0 && <span className="mt-1 block font-sans text-[10px] text-muted-foreground">{row.unknownCostRuns} unpriced</span>}</td><td className={td}>{number(row.retries)}</td><td className={td}>{number(row.toolCalls)}</td></tr>)}</tbody></table>{!rows.length && <p className="p-4 text-xs text-muted-foreground">No agent runs recorded in this period.</p>}</div></section>;
}
