import { WorkspaceLink as Link } from "@/components/app/workspace-link";
import { BarChart3, ArrowUpRight, BookOpen } from "lucide-react";
import { PageHeader } from "@/components/app/page-header";
import { EmptyState } from "@/components/app/empty-state";
import { NewWorkflowButton } from "@/components/app/new-workflow-button";
import type { IntelligenceData, IntelligenceFilters } from "@/types/intelligence";
import { IntelligenceFilterControls } from "./intelligence-filters";
import { SegmentTable, UsageTable, WorkflowComparison } from "./intelligence-tables";
import { number, money, percent } from "./format";
import { WorkflowExecutionTable } from "./workflow-execution-table";

export function IntelligenceWorkspace({ data, error, filters, configured = true }: { data?: IntelligenceData; error?: string; filters?: Partial<IntelligenceFilters>; configured?: boolean }) {
  return <div className="flex min-w-0 flex-col gap-6">
    <PageHeader eyebrow="Intelligence / Outcomes over time" title="Product intelligence" description="Understand your funnel, research quality and the cost of recorded agent work." actions={<NewWorkflowButton />} />
    <IntelligenceFilterControls key={JSON.stringify(filters)} data={data} filters={filters ?? data?.filters} />
    {error && <div role="alert" className="rounded-md border border-[var(--danger-border)] bg-[var(--danger-bg)] p-4 text-xs leading-5 text-destructive">{error} <Link href="/intelligence" className="font-medium underline">Reset filters</Link></div>}
    {!data ? <EmptyState icon={BarChart3} title={configured ? "Intelligence is unavailable" : "Build intelligence from persisted work"} description={configured ? "Refresh after checking database migrations and workspace access." : "Connect a workspace and run a research workflow to collect real outcomes. Sample data stays separate from live intelligence."} action={<Link href={configured ? "/workflows" : "/sign-in"} className="interactive-link text-xs font-medium text-primary hover:underline">{configured ? "Open research workflows" : "Open sign in"}</Link>} /> : <>
      <p className="text-[11px] leading-5 text-muted-foreground">{data.period.cohortLabel}. Funnel counts use distinct company–workflow pairs. Estimated cost covers whole matching workflows.</p>
      <details className="rounded-md border border-border bg-card px-4 py-3"><summary className="flex w-fit cursor-pointer items-center gap-2 rounded text-xs font-medium focus-visible:outline-2 focus-visible:outline-ring"><BookOpen aria-hidden className="size-3.5 text-muted-foreground" />How to read these metrics</summary><dl className="mt-4 grid gap-x-8 gap-y-4 text-xs sm:grid-cols-2"><div><dt className="font-medium">Company–workflow cohort</dt><dd className="mt-1 leading-6 text-muted-foreground">The period selects workflows by creation date. A company researched in two workflows counts once in each; outcomes reflect their saved history.</dd></div><div><dt className="font-medium">Stage conversion</dt><dd className="mt-1 leading-6 text-muted-foreground">Companies at a stage divided by companies at the previous stage. A zero denominator displays —. The first stage has no conversion rate.</dd></div><div><dt className="font-medium">Unknown usage and cost</dt><dd className="mt-1 leading-6 text-muted-foreground">— and Unavailable indicate missing evidence, usage or pricing. They are not measured zeros. Estimated AI cost uses recorded model usage and is not a billing total.</dd></div><div><dt className="font-medium">Observed replies</dt><dd className="mt-1 leading-6 text-muted-foreground">Only detected replies count. Missing mailbox coverage cannot prove no reply; reply conversion remains unavailable without verified monitoring coverage.</dd></div></dl></details>
      <dl className="grid grid-cols-2 gap-x-6 gap-y-5 border-b border-border pb-6 md:grid-cols-3 xl:grid-cols-6">{[
        { label: "Companies researched", value: number(data.summary.researched) }, { label: "Qualified leads", value: number(data.summary.qualified) },
        { label: "Companies contacted", value: number(data.summary.sent) }, { label: "Companies with replies", value: number(data.summary.replies) },
        { label: "Estimated AI cost · cohort", value: money(data.summary.estimatedCostUsd) }, { label: "Average lead score", value: number(data.summary.averageScore, 1) },
      ].map((metric) => <div key={metric.label} className="flex flex-col gap-2"><dt className="section-label leading-4">{metric.label}</dt><dd className="font-mono text-[25px] font-medium tracking-tight tabular-nums">{metric.value}</dd></div>)}</dl>
      {data.insights.length > 0 && <ul className="flex flex-col gap-2 border-l-2 border-[var(--brand-accent)] pl-4 text-xs leading-5 text-muted-foreground">{data.insights.map((insight) => <li key={insight.key}>{insight.text}</li>)}</ul>}
      {!data.filterOptions.workflows.length && <EmptyState icon={BarChart3} title="No workflow history yet" description="Run your first research workflow to start building intelligence." action={<NewWorkflowButton />} />}
      <div className="grid min-w-0 items-start gap-7 xl:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
        <section aria-labelledby="lead-funnel"><div className="mb-3"><h2 id="lead-funnel" className="text-sm font-semibold">Lead funnel</h2><p className="mt-1 text-[11px] text-muted-foreground">Stage conversion uses the previous recorded stage.</p></div><div className="overflow-hidden rounded-lg border border-border bg-card"><table className="w-full text-left text-xs"><thead className="border-b border-border bg-muted/30 text-[10px] text-muted-foreground"><tr><th scope="col" className="px-4 py-3 font-medium">Recorded stage</th><th scope="col" className="px-4 py-3 text-right font-medium">Companies</th><th scope="col" className="px-4 py-3 text-right font-medium">Conversion</th></tr></thead><tbody className="divide-y divide-border">{data.funnel.map((stage) => <tr key={stage.key}><th scope="row" className="px-4 py-3 font-normal">{stage.label}</th><td className="px-4 py-3 text-right font-mono tabular-nums">{number(stage.count)}</td><td className="px-4 py-3 text-right font-mono tabular-nums text-muted-foreground">{percent(stage.conversionRate)}</td></tr>)}</tbody></table></div><p className="mt-2 text-[10px] leading-5 text-muted-foreground">Detected replies are an observed lower bound. Reply rate is unavailable without verified monitoring coverage.</p></section>
        <section aria-labelledby="historical-trends" className="min-w-0"><div className="mb-3"><h2 id="historical-trends" className="text-sm font-semibold">Historical cohorts</h2><p className="mt-1 text-[11px] text-muted-foreground">Outcomes grouped by workflow creation date.</p></div><div tabIndex={0} role="region" aria-label="Historical cohort table, scroll horizontally or vertically" className="max-h-[365px] overflow-auto rounded-lg border border-border bg-card focus-visible:outline-2 focus-visible:outline-ring"><table className="w-full min-w-[390px] text-left text-[11px]"><thead className="sticky top-0 border-b border-border bg-card text-[10px] text-muted-foreground"><tr>{["Created", "Researched", "Qualified", "Sent", "Replies"].map((label) => <th key={label} scope="col" className="px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-border">{data.trends.map((day) => <tr key={day.date}><th scope="row" className="px-3 py-3 font-mono font-normal">{day.date}</th>{[day.researched, day.qualified, day.sent, day.replies].map((value, index) => <td key={index} className="px-3 py-3 font-mono tabular-nums">{number(value)}</td>)}</tr>)}</tbody></table>{!data.trends.length && <p className="p-5 text-xs text-muted-foreground">No workflows were created in this period.</p>}</div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-[11px] text-muted-foreground">{data.workflowStatuses.map((stage) => <span key={stage.key}>{stage.key.replaceAll("_", " ")} <strong className="ml-1 font-mono font-medium text-foreground">{stage.count}</strong></span>)}</div></section>
      </div>
      <WorkflowComparison workflows={data.workflows} truncated={data.workflowTableTruncated} />
      <WorkflowExecutionTable workflows={data.workflows} />
      <section className="border-t border-border pt-5"><h2 className="text-sm font-semibold">Workflow milestones</h2><p className="mt-1 text-[11px] leading-5 text-muted-foreground">Distinct workflows with persisted milestone evidence. Research-only plans can finish without outreach.</p><dl className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-4">{data.workflowFunnel.map((stage) => <div key={stage.key}><dt className="text-[11px] text-muted-foreground">{stage.label}</dt><dd className="mt-1 font-mono text-lg tabular-nums">{stage.count}</dd></div>)}</dl></section>
      <section className="min-w-0 border-t border-border pt-6"><h2 className="text-sm font-semibold">Research & opportunity intelligence</h2><p className="mt-1 text-[11px] leading-5 text-muted-foreground">Historical research snapshots retain original scores. Segment associations describe evidence; they do not establish causation.</p><dl className="my-5 grid grid-cols-2 gap-5 lg:grid-cols-4">{[
        ["Average sources / company", number(data.researchQuality.averageSources, 1)], ["Without usable evidence", number(data.researchQuality.withoutEvidence)],
        ["High confidence research", number(data.researchQuality.highConfidence)], ["Research failures", number(data.researchQuality.failures)],
      ].map(([label, value]) => <div key={label}><dt className="text-[11px] text-muted-foreground">{label}</dt><dd className="mt-2 font-mono text-xl tabular-nums">{value}</dd></div>)}</dl><p className="mb-5 text-[11px] text-muted-foreground">{data.researchQuality.partialFailureWorkflows} workflows with partial research failures · {data.researchQuality.insufficientEvidence} rejected for insufficient evidence · {data.researchQuality.unknownSnapshots} missing historical snapshots</p>
        <SegmentTable title="Automation opportunities" segments={data.opportunities} />
        <details className="mt-5"><summary className="w-fit cursor-pointer rounded text-xs font-medium focus-visible:outline-2 focus-visible:outline-ring">Compare industries, locations, sources & saved strategy</summary><div className="mt-5 flex flex-col gap-6"><SegmentTable title="Industries" segments={data.industries} /><SegmentTable title="Locations" segments={data.locations} /><SegmentTable title="Research source categories" segments={data.sources} /><SegmentTable title="Ideal customer profiles · historical snapshots" segments={data.icps} /><SegmentTable title="Workflow templates · historical snapshots" segments={data.templates} /></div></details>
      </section>
      <section className="min-w-0 border-t border-border pt-6"><h2 className="text-sm font-semibold">Agent operations & estimated cost</h2><p className="mt-1 text-[11px] leading-5 text-muted-foreground">Agent and model usage count runs recorded in the selected period, with the same strategy filters. These measure execution, duration and consumption.</p>
        <dl className="my-5 grid gap-5 sm:grid-cols-3">{[["Today · workspace", data.costPeriods.today], ["Last 7 days · workspace", data.costPeriods.last7Days], ["Last 30 days · workspace", data.costPeriods.last30Days]].map(([label, cost]) => {
          const metric = cost as IntelligenceData["costPeriods"]["today"];
          return <div key={String(label)}><dt className="text-[11px] text-muted-foreground">Estimated AI cost · {String(label)}</dt><dd className="mt-2 font-mono text-xl tabular-nums">{money(metric.estimatedCostUsd)}</dd><p className="mt-1 text-[10px] text-muted-foreground">{metric.unknownCostRuns > 0 ? `${metric.unknownCostRuns} unpriced runs · known subtotal ${money(metric.knownEstimatedCostUsd)}` : "Recorded model usage"}</p></div>;
        })}</dl><div className="flex flex-col gap-6"><UsageTable title="Agent performance" rows={data.agents} /><UsageTable title="Model usage" rows={data.models} /></div>
        <dl className="mt-5 grid grid-cols-2 gap-5 lg:grid-cols-4">{[["Execution attempts · cohort", data.summary.executionsAttempted], ["Messages sent · cohort", data.summary.messagesSent], ["Reply observations · cohort", data.summary.repliesDetected], ["Failed jobs · cohort", data.summary.failedJobs], ["Needs attention · cohort", data.summary.needsAttention], ["Pending email proposals · cohort", data.summary.pendingApprovals], ["Follow-ups scheduled · cohort", data.summary.followupsScheduled], ["Follow-ups completed · cohort", data.summary.followupsCompleted]].map(([label, value]) => <div key={label}><dt className="text-[11px] text-muted-foreground">{label}</dt><dd className="mt-1 font-mono text-lg tabular-nums">{value}</dd></div>)}</dl>
      </section>
      <div className="flex flex-wrap items-center justify-between gap-3 border-t border-border pt-4 text-[11px] text-muted-foreground"><span>Estimated costs use recorded Release 0.7 pricing. Unknown usage remains unavailable.</span><Link href="/icps" className="inline-flex items-center gap-1.5 rounded hover:text-foreground focus-visible:outline-2 focus-visible:outline-ring">Reuse your strategy<ArrowUpRight className="size-3" /></Link></div>
    </>}
  </div>;
}
