import Link from "next/link";
import { Building2, ChevronRight } from "lucide-react";
import type { Company } from "@/types/domain";
import { EmptyState } from "@/components/app/empty-state";
import { LeadScore } from "@/components/app/lead-score";
import { StatusBadge } from "@/components/app/status-badge";

export function WorkflowCompanies({ companies, total }: { companies: Company[]; total: number }) {
  return <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="text-sm font-semibold">Discovered companies</h2><p className="mt-0.5 text-xs text-muted-foreground">Representative demo profiles connected to this workflow</p></div><span className="font-mono text-xs tabular-nums text-muted-foreground">{companies.length} of {total} shown</span></div>{companies.length === 0 ? <EmptyState icon={Building2} title="No companies researched yet" description="Companies will appear here when this workflow reaches discovery. This demo plan has not run external research." /> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-[#111519] text-[10px] uppercase tracking-[0.07em] text-[#87929b]"><tr><th className="px-5 py-3 font-medium">Company</th><th className="px-4 py-3 font-medium">Industry</th><th className="px-4 py-3 font-medium">Opportunity</th><th className="px-4 py-3 font-medium">Score</th><th className="px-4 py-3 font-medium">Research</th><th className="w-8 px-3 py-3"><span className="sr-only">Open</span></th></tr></thead><tbody className="divide-y divide-border">{companies.map((company) => <tr key={company.id} className="hover:bg-[#1a1f23]"><td className="px-5 py-3"><Link href={`/companies?company=${company.id}`} className="font-medium text-foreground hover:text-[#b9d8cf]">{company.name}</Link></td><td className="px-4 py-3 text-muted-foreground">{company.industry}</td><td className="max-w-[240px] truncate px-4 py-3 text-[#c4cdd1]" title={company.opportunity}>{company.opportunity}</td><td className="px-4 py-3"><LeadScore score={company.score} /></td><td className="px-4 py-3"><StatusBadge status={company.researchStatus} /></td><td className="px-3 py-3"><Link href={`/companies?company=${company.id}`} aria-label={`Inspect ${company.name}`}><ChevronRight className="size-3.5 text-muted-foreground" /></Link></td></tr>)}</tbody></table></div>}</section>;
}
